name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v2
        with:
          publish-script: pnpm run release
          version-script: pnpm run changeset version
          commit-message: "chore: version packages"
          pr-title: "chore: version packages"
          github-token: ${{ secrets.GITHUB_TOKEN }}
